version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "7755:80"
    depends_on:
      - api
    volumes:
      - ./docker-config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./src/laravel:/var/www

  api:
    build:
      context: ./docker-config/php
      dockerfile: Dockerfile
    depends_on:
      - mysql
    volumes:
      - ./src/laravel:/var/www

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: sample
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data: